### PR TITLE
Explained how to ignore words in aspell

### PR DESCRIPTION
**Pull request by kevinywlui**
Explained how to ignore words in aspell following
http://aspell.net/man-html/Format-of-the-Personal-and-Replacement-Dictionaries.html#Format-of-the-Personal-and-Replacement-Dictionaries

### CODE REVIEW

**Comment by haraldschilly** [comment]
ah, that's very cool. I've two comments:

* this is also applicable to any text files (not just latex), e.g. markdown. Hence it might be better to move this into a dedicated "howto/..." page and link to it? FYI, adding a page to `howto/...` implies to include it in the  [howto index page](https://github.com/sagemathinc/cocalc-doc/blob/master/source/howto/index.rst) ... the latex section is fine, because I don't think we have a page for markdown/rst/html editor yet, do we @DrXyzzy ?

* I think `Then add one words` → `Then add one word` corrects a spelling mistake.

**Comment by DrXyzzy** [comment]
@haraldschilly 

> I don't think we have a page for markdown/rst/html editor yet

We don't have them yet.

This is a nice contribution. I suggest merge & commit asap and refactor/updatw index after the merge.

**Comment by haraldschilly** [comment]
ok, I made https://github.com/sagemathinc/cocalc-doc/issues/8

**Comment by DrXyzzy** [comment]
> I don't think we have a page for markdown/rst/html editor yet

We do now, at https://doc.cocalc.com/frame-editor.html

**Pull request merged**
